#!/usr/bin/env bash


if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ./ -mindepth 1 -maxdepth 4 -type d | sed 's|^\./||' | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

path=$(pwd)/$selected

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $path
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -s $selected_name -c $path
    exit 0
fi

tmux attach -t $selected_name
